CREATE TABLE expense_categories (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(100) NOT NULL UNIQUE,
    icon    VARCHAR(50),
    color   VARCHAR(20)
);

CREATE TABLE expense_sub_categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT       NOT NULL REFERENCES expense_categories(id) ON DELETE CASCADE,
    name        VARCHAR(100) NOT NULL,
    icon        VARCHAR(50)
);

CREATE TABLE incomes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name        VARCHAR(255)   NOT NULL,
    amount      NUMERIC(15, 2) NOT NULL,
    frequency   VARCHAR(20)    NOT NULL,
    income_type VARCHAR(20)    NOT NULL,
    active      BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP(6)   NOT NULL,
    updated_at  TIMESTAMP(6)
);

CREATE TABLE deductions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    income_id      BIGINT         NOT NULL REFERENCES incomes(id) ON DELETE CASCADE,
    name           VARCHAR(255)   NOT NULL,
    deduction_type VARCHAR(30)    NOT NULL,
    is_percentage  BOOLEAN        NOT NULL DEFAULT TRUE,
    value          NUMERIC(10, 4) NOT NULL,
    created_at     TIMESTAMP(6)   NOT NULL
);

CREATE TABLE expenses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    category_id     BIGINT         NOT NULL REFERENCES expense_categories(id),
    sub_category_id BIGINT         REFERENCES expense_sub_categories(id),
    description     VARCHAR(255)   NOT NULL,
    amount          NUMERIC(15, 2) NOT NULL,
    expense_type    VARCHAR(20)    NOT NULL,
    expense_date    DATE           NOT NULL,
    frequency       VARCHAR(20),
    due_day         INTEGER,
    notes           TEXT,
    active          BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP(6)   NOT NULL,
    updated_at      TIMESTAMP(6)
);

-- Índices
CREATE INDEX idx_incomes_user_id    ON incomes(user_id);
CREATE INDEX idx_expenses_user_id   ON expenses(user_id);
CREATE INDEX idx_expenses_date      ON expenses(expense_date);
CREATE INDEX idx_expenses_category  ON expenses(category_id);
CREATE INDEX idx_deductions_income  ON deductions(income_id);

-- Categorías por defecto
INSERT INTO expense_categories (name, icon, color) VALUES
('Hogar',        'home',        '#4A90D9'),
('Alimentación', 'restaurant',  '#E67E22'),
('Transporte',   'directions_car', '#27AE60'),
('Salud',        'local_hospital', '#E74C3C'),
('Entretenimiento', 'movie',    '#9B59B6'),
('Educación',    'school',      '#3498DB'),
('Ropa',         'shopping_bag','#E91E63'),
('Inversiones',  'trending_up', '#2ECC71'),
('Otros',        'more_horiz',  '#95A5A6');

-- Subcategorías por defecto
INSERT INTO expense_sub_categories (category_id, name) VALUES
(1, 'Alquiler/Hipoteca'),
(1, 'Electricidad'),
(1, 'Agua'),
(1, 'Internet'),
(1, 'Netflix/Streaming'),
(1, 'Préstamo del hogar'),
(2, 'Supermercado'),
(2, 'Restaurantes'),
(2, 'Delivery'),
(3, 'Gasolina'),
(3, 'Transporte público'),
(3, 'Uber/Taxi'),
(4, 'Médico'),
(4, 'Medicamentos'),
(4, 'Seguro médico'),
(5, 'Cine/Teatro'),
(5, 'Videojuegos'),
(5, 'Salidas');
