CREATE TABLE budgets (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    category_id  BIGINT         REFERENCES expense_categories(id),
    limit_amount NUMERIC(15, 2) NOT NULL,
    year         INTEGER        NOT NULL,
    month        INTEGER        NOT NULL,
    active       BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP(6)   NOT NULL,
    updated_at   TIMESTAMP(6),
    CONSTRAINT uk_budget_user_category_period
        UNIQUE (user_id, category_id, year, month)
);

CREATE TABLE savings_goals (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name         VARCHAR(255)   NOT NULL,
    fixed_amount NUMERIC(15, 2),
    percentage   NUMERIC(5, 2),
    active       BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP(6)   NOT NULL,
    updated_at   TIMESTAMP(6),
    CONSTRAINT chk_savings_goal_has_value
        CHECK (fixed_amount IS NOT NULL OR percentage IS NOT NULL)
);

CREATE INDEX idx_budgets_user_id    ON budgets(user_id);
CREATE INDEX idx_budgets_period     ON budgets(user_id, year, month);
CREATE INDEX idx_savings_goals_user ON savings_goals(user_id);
