CREATE TABLE IF NOT EXISTS notifications (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title          VARCHAR(255) NOT NULL,
    message        TEXT         NOT NULL,
    type           VARCHAR(30)  NOT NULL,
    channel        VARCHAR(10)  NOT NULL,
    read           BOOLEAN      NOT NULL DEFAULT FALSE,
    sent           BOOLEAN      NOT NULL DEFAULT FALSE,
    reference_id   BIGINT,
    reference_type VARCHAR(50),
    scheduled_at   TIMESTAMP(6),
    sent_at        TIMESTAMP(6),
    created_at     TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS reminders (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expense_id    BIGINT       REFERENCES expenses(id) ON DELETE SET NULL,
    title         VARCHAR(255) NOT NULL,
    message       TEXT,
    channel       VARCHAR(10)  NOT NULL,
    day_of_month  INTEGER,
    remind_at     TIMESTAMP(6),
    recurring     BOOLEAN      NOT NULL DEFAULT FALSE,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP(6) NOT NULL,
    CONSTRAINT chk_reminder_has_schedule
        CHECK (day_of_month IS NOT NULL OR remind_at IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id    ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_read       ON notifications(user_id, read);
CREATE INDEX IF NOT EXISTS idx_notifications_created    ON notifications(created_at);
CREATE INDEX IF NOT EXISTS idx_reminders_user_id        ON reminders(user_id);
CREATE INDEX IF NOT EXISTS idx_reminders_day_of_month   ON reminders(day_of_month) WHERE active = true;
CREATE INDEX IF NOT EXISTS idx_reminders_remind_at      ON reminders(remind_at) WHERE active = true AND recurring = false;
