CREATE TABLE file_attachments (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expense_id        BIGINT                REFERENCES expenses(id) ON DELETE SET NULL,
    original_filename VARCHAR(255) NOT NULL,
    stored_filename   VARCHAR(255) NOT NULL,
    content_type      VARCHAR(100) NOT NULL,
    file_size         BIGINT       NOT NULL,
    storage_provider  VARCHAR(50)  NOT NULL,
    file_url          VARCHAR(500) NOT NULL,
    storage_key       VARCHAR(500),
    description       VARCHAR(500),
    active            BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMP    NOT NULL DEFAULT NOW()
);
