CREATE TABLE IF NOT EXISTS file_attachments (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expense_id        BIGINT        REFERENCES expenses(id) ON DELETE SET NULL,
    original_filename VARCHAR(255)  NOT NULL,
    stored_filename   VARCHAR(255)  NOT NULL,
    content_type      VARCHAR(100)  NOT NULL,
    file_size         BIGINT        NOT NULL,
    storage_provider  VARCHAR(20)   NOT NULL,  -- LOCAL, S3, CLOUDINARY
    file_url          TEXT          NOT NULL,
    storage_key       VARCHAR(500),
    description       TEXT,
    active            BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMP(6)  NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_file_attachments_user_id    ON file_attachments(user_id);
CREATE INDEX IF NOT EXISTS idx_file_attachments_expense_id ON file_attachments(expense_id);
CREATE INDEX IF NOT EXISTS idx_file_attachments_active     ON file_attachments(user_id, active);
